;;;;; Converted from the "Vertices" Processing example at:
;;;;; "http://www.processing.org/learning/examples/vertices.html"
;;;;; (C)2006 Luke J Crook

(in-package #:sdl-gfx-examples) 


(defun vertices ()
  (let ((width 200) (height 200))
    (sdl:with-init ()
      (sdl:window width height :title-caption "Vertices, from Processing.org")
      (sdl:clear-display (sdl:color :r 0 :g 0 :b 0))
      (sdl:with-surface (disp sdl:*default-display*)
	(sdl:with-color (col (sdl:color :r 102 :g 102 :b 102))
	  (sdl-gfx:with-curve (:line-strip 10)
	    (sdl-gfx:add-vertex-* 168 182)
	    (sdl-gfx:add-vertex-* 168 182)
	    (sdl-gfx:add-vertex-* 136 38)
	    (sdl-gfx:add-vertex-* 42 34)
	    (sdl-gfx:add-vertex-* 64 200)
	    (sdl-gfx:add-vertex-* 64 200)))
	(sdl:with-color (col (sdl:color :r 51 :g 51 :b 51))
	  (sdl-gfx:with-shape (:lines)
	    (sdl-gfx:add-vertex-* 60 40)
	    (sdl-gfx:add-vertex-* 160 10)
	    (sdl-gfx:add-vertex-* 170 150)
	    (sdl-gfx:add-vertex-* 60 150)))
	(sdl:with-color (col (sdl:color :r 255 :g 255 :b 255))
	  (sdl-gfx:with-shape (:points)
	    (sdl-gfx:add-vertex-* 60 40)
	    (sdl-gfx:add-vertex-* 160 10)
	    (sdl-gfx:add-vertex-* 170 150)
	    (sdl-gfx:add-vertex-* 60 150)))
	(sdl:with-color (col (sdl:color :r 126 :g 126 :b 126))
	  (sdl-gfx:with-bezier (10)
	    (sdl-gfx:add-vertex-* 60 40)
	    (sdl-gfx:add-vertex-* 160 10)
	    (sdl-gfx:add-vertex-* 170 150)
	    (sdl-gfx:add-vertex-* 60 150))))
      (sdl:with-events ()
	(:quit-event () t)
	(:video-expose-event () (sdl:update-display))))))

