#### -*- Mode: Makefile -*-

CC=gcc
SHFLAGS=-shared -fPIC
CFLAGS+=$(SHFLAGS) -g -Wall
LDFLAGS+=$(SHFLAGS) -L/usr/X11R6/lib/
SHLIB_SUFFIX=so
SDL_CONFIG=sdl-config

SDL_CFLAGS=$(CFLAGS) $(shell $(SDL_CONFIG) --cflags)
SDL_LDFLAGS=$(LDFLAGS) $(shell $(SDL_CONFIG) --libs)

SDL_GLUE_CFLAGS=$(SDL_CFLAGS)
SDL_GLUE_LDFLAGS=$(SDL_LDFLAGS) -lSDL_ttf
