#### -*- Mode: Makefile -*-
#### Author: Matthew Danish <mrd@debian.org>
#### Common Makefile options

#### Modified by: Luke Crook <luke@balooga.com>

LIB_NAME=lispbuilder-sdl-ttf-glue
SO_LIB_NAME=lib$(LIB_NAME)

STUBS=  $(SO_LIB_NAME).$(SHLIB_SUFFIX)

