#### -*- Mode: Makefile -*-

CC=gcc
SHFLAGS=-shared -fPIC
CFLAGS+=$(SHFLAGS) -g -Wall
LDFLAGS+=$(SHFLAGS) -L/usr/X11R6/lib/
SHLIB_SUFFIX=so
SDL_CONFIG=sdl-config

SDL_CFLAGS=$(shell $(SDL_CONFIG) --cflags) $(CFLAGS)
SDL_LDFLAGS=$(shell $(SDL_CONFIG) --libs) $(LDFLAGS)

SDL_TTF_CFLAGS=$(SDL_CFLAGS)
SDL_TTF_LDFLAGS=$(SDL_LDFLAGS) -lSDL_ttf
