;;; -*- lisp -*-

(in-package #:cl-user)

(defpackage #:lispbuilder-sdl-mixer
  (:use #:cl #:cffi)
  (:nicknames #:sdl-mixer)
  (:documentation "The main package of `lispbuilder-sdl-mixer'.")
  (:import-from #:lispbuilder-sdl-mixer-cffi

		 lispbuilder-sdl-cffi::+SDL-MIXER-MAJOR-VERSION+
		 lispbuilder-sdl-cffi::+SDL-MIXER-MINOR-VERSION+
		 lispbuilder-sdl-cffi::+SDL-MIXER-PATCHLEVEL+
		 lispbuilder-sdl-cffi::+MAJOR-VERSION+
		 lispbuilder-sdl-cffi::+MINOR-VERSION+
		 lispbuilder-sdl-cffi::+PATCHLEVEL+
		 lispbuilder-sdl-cffi::Linked-Version
		 lispbuilder-sdl-cffi::+CHANNELS+
		 lispbuilder-sdl-cffi::+DEFAULT-FREQUENCY+
		 lispbuilder-sdl-cffi::+DEFAULT-CHANNELS+
		 lispbuilder-sdl-cffi::+MAX-VOLUME+
		 lispbuilder-sdl-cffi::Chunk
		 lispbuilder-sdl-cffi::allocated
		 lispbuilder-sdl-cffi::abuf
		 lispbuilder-sdl-cffi::alen
		 lispbuilder-sdl-cffi::volume
		 lispbuilder-sdl-cffi::Fading
		 lispbuilder-sdl-cffi::Music-Type
		 lispbuilder-sdl-cffi::Open-Audio
		 lispbuilder-sdl-cffi::Allocate-Channels
		 lispbuilder-sdl-cffi::Query-Spec
		 lispbuilder-sdl-cffi::Load-WAV-RW
		 lispbuilder-sdl-cffi::Load-MUS-RW
		 lispbuilder-sdl-cffi::Quick-Load-WAV
		 lispbuilder-sdl-cffi::Quick-Load-RAW
		 lispbuilder-sdl-cffi::Free-Chunk
		 lispbuilder-sdl-cffi::Free-Music
		 lispbuilder-sdl-cffi::Get-Music-Type
		 lispbuilder-sdl-cffi::Set-Post-Mix
		 lispbuilder-sdl-cffi::Hook-Music
		 lispbuilder-sdl-cffi::Hook-Music-Finished
		 lispbuilder-sdl-cffi::Get-Music-Hook-Data
		 lispbuilder-sdl-cffi::Channel-Finished
		 lispbuilder-sdl-cffi::+CHANNEL-POST+
		 lispbuilder-sdl-cffi::Register-Effect
		 lispbuilder-sdl-cffi::Unregister-Effect
		 lispbuilder-sdl-cffi::Unregister-All-Effects
		 lispbuilder-sdl-cffi::Set-Panning
		 lispbuilder-sdl-cffi::Set-Position
		 lispbuilder-sdl-cffi::Set-Distance
		 lispbuilder-sdl-cffi::Set-Reverse-Stereo
		 lispbuilder-sdl-cffi::Reserve-Channels
		 lispbuilder-sdl-cffi::Group-Channel
		 lispbuilder-sdl-cffi::Group-Channels
		 lispbuilder-sdl-cffi::Group-Available
		 lispbuilder-sdl-cffi::Group-Count
		 lispbuilder-sdl-cffi::Group-Oldest
		 lispbuilder-sdl-cffi::Group-Newer
		 lispbuilder-sdl-cffi::Play-Channel-Timed
		 lispbuilder-sdl-cffi::Play-Music
		 lispbuilder-sdl-cffi::Fade-In-Music
		 lispbuilder-sdl-cffi::Fade-In-Music-Pos
		 lispbuilder-sdl-cffi::Fade-In-Channel-Timed
		 lispbuilder-sdl-cffi::Volume
		 lispbuilder-sdl-cffi::Volume-Chunk
		 lispbuilder-sdl-cffi::Volume-Music
		 lispbuilder-sdl-cffi::Halt-Channel
		 lispbuilder-sdl-cffi::Halt-Group
		 lispbuilder-sdl-cffi::Halt-Music
		 lispbuilder-sdl-cffi::Expire-Channel
		 lispbuilder-sdl-cffi::Fade-Out-Channel
		 lispbuilder-sdl-cffi::Fade-Out-Group
		 lispbuilder-sdl-cffi::Fade-Out-Music
		 lispbuilder-sdl-cffi::Fading-Music
		 lispbuilder-sdl-cffi::Fading-Channel
		 lispbuilder-sdl-cffi::Pause
		 lispbuilder-sdl-cffi::Resume
		 lispbuilder-sdl-cffi::Paused
		 lispbuilder-sdl-cffi::Pause-Music
		 lispbuilder-sdl-cffi::Resume-Music
		 lispbuilder-sdl-cffi::Rewind-Music
		 lispbuilder-sdl-cffi::Paused-Music
		 lispbuilder-sdl-cffi::Set-Music-Position
		 lispbuilder-sdl-cffi::Playing
		 lispbuilder-sdl-cffi::Playing-Music
		 lispbuilder-sdl-cffi::Set-Music-CMD
		 lispbuilder-sdl-cffi::Set-Synchro-Value
		 lispbuilder-sdl-cffi::Get-Synchro-Value
		 lispbuilder-sdl-cffi::Close-Audio
   

		 lispbuilder-sdl-cffi::SDL-MIXER-VERSION
		 lispbuilder-sdl-cffi::VERSION
		 lispbuilder-sdl-cffi::+DEFAULT-FORMAT+

		 lispbuilder-sdl-cffi::Play-Channel
		 lispbuilder-sdl-cffi::Fade-In-Channel
		 lispbuilder-sdl-cffi::Get-Error

		 lispbuilder-sdl-cffi::free
		 lispbuilder-sdl-cffi::this-fp
		 lispbuilder-sdl-cffi::gc-p
		 lispbuilder-sdl-cffi::simple-free)

  (:export

   #:+SDL-MIXER-MAJOR-VERSION+
   #:+SDL-MIXER-MINOR-VERSION+
   #:+SDL-MIXER-PATCHLEVEL+
   #:+MAJOR-VERSION+
   #:+MINOR-VERSION+
   #:+PATCHLEVEL+
   #:Linked-Version
   #:+CHANNELS+
   #:+DEFAULT-FREQUENCY+
   #:+DEFAULT-CHANNELS+
   #:+MAX-VOLUME+
   #:Chunk
   #:allocated
   #:abuf
   #:alen
   #:volume
   #:Fading
   #:Music-Type
   #:Open-Audio
   #:Allocate-Channels
   #:Query-Spec
   #:Load-WAV-RW
   #:Load-MUS
   #:Load-MUS-RW
   #:Quick-Load-WAV
   #:Quick-Load-RAW
   #:Free-Chunk
   #:Free-Music
   #:Get-Music-Type
   #:Set-Post-Mix
   #:Hook-Music
   #:Hook-Music-Finished
   #:Get-Music-Hook-Data
   #:Channel-Finished
   #:+CHANNEL-POST+
   #:Register-Effect
   #:Unregister-Effect
   #:Unregister-All-Effects
   #:Set-Panning
   #:Set-Position
   #:Set-Distance
   #:Set-Reverse-Stereo
   #:Reserve-Channels
   #:Group-Channel
   #:Group-Channels
   #:Group-Available
   #:Group-Count
   #:Group-Oldest
   #:Group-Newer
   #:Play-Channel-Timed
   #:Play-Music
   #:Fade-In-Music
   #:Fade-In-Music-Pos
   #:Fade-In-Channel-Timed
   #:Volume
   #:Volume-Chunk
   #:Volume-Music
   #:Halt-Channel
   #:Halt-Group
   #:Halt-Music
   #:Expire-Channel
   #:Fade-Out-Channel
   #:Fade-Out-Group
   #:Fade-Out-Music
   #:Fading-Music
   #:Fading-Channel
   #:Pause
   #:Resume
   #:Paused
   #:Pause-Music
   #:Resume-Music
   #:Rewind-Music
   #:Paused-Music
   #:Set-Music-Position
   #:Playing
   #:Playing-Music
   #:Set-Music-CMD
   #:Set-Synchro-Value
   #:Get-Synchro-Value
   #:Get-Chunk
   #:Close-Audio
   

   #:SDL-MIXER-VERSION
   #:VERSION
   #:+DEFAULT-FORMAT+
   #:Load-WAV
   #:Play-Channel
   #:Fade-In-Channel
   #:Get-Error

   #:free
   #:this-fp
   #:gc-p
   #:simple-free))