
(in-package #:sdl-examples)

(defun active-event ()
  (let ((text ""))
    (sdl:with-init ()
      (sdl:window 320 200 :title-caption ":ACTIVE-EVENT" :icon-caption "ACTIVE-EVENT")
      (sdl:initialise-default-font)
      (sdl:with-events ()
        (:active-event (:gain gain :state state)
         (when (sdl:mouse-focus-p state)
           (if (sdl:mouse-gain-focus-p gain state)
             (setf text "Event: Window gained mouse focus")
             (setf text "Event: Window lost   mouse focus"))))
        (:key-down-event ()
         (when (sdl:key-down-p :sdl-key-escape)
           (sdl:push-quit-event)))
        (:quit-event () t)
        (:video-expose-event () (sdl:update-display))
        (:idle ()
         (sdl:clear-display sdl:*black*)
         (sdl:draw-string-solid (if (sdl:mouse-focus-p)
                                  "State: Mouse over Window"
                                  "State: Mouse left Window")
                                #(10 10) :surface sdl:*default-display* :color sdl:*white*)
         (sdl:draw-string-solid text #(10 20) :surface sdl:*default-display* :color sdl:*white*)
         (sdl:update-display))))))
