;;;;; Converted from the "Vertices" Processing example at:
;;;;; "http://www.processing.org/learning/examples/vertices.html"
;;;;; (C)2006 Luke J Crook

(in-package #:sdl-examples) 


(defun vertices ()
  (let ((width 200) (height 200))
    (sdl:with-init ()
      (sdl::window width height :title-caption "Vertices, from Processing.org")
      (sdl::clear-display (sdl::color))
      (sdl::with-surface (surf sdl::*default-display*)
	(sdl::with-color (a-col (sdl::color :r 102 :g 102 :b 102))
	  (sdl::with-curve (:line-strip 10)
	    (sdl::add-vertex (sdl::point :x 168 :y 182))
	    (sdl::add-vertex (sdl::point :x 168 :y 182))
	    (sdl::add-vertex (sdl::point :x 136 :y 38))
	    (sdl::add-vertex (sdl::point :x 42 :y 34))
	    (sdl::add-vertex (sdl::point :x 64 :y 200))
	    (sdl::add-vertex (sdl::point :x 64 :y 200))))
	(sdl::with-color (a-col (sdl::color :r 51 :g 51 :b 51))
	  (sdl::with-shape (:lines)
	    (sdl::add-vertex (sdl::point :x 60 :y 40))
	    (sdl::add-vertex (sdl::point :x 160 :y 10))
	    (sdl::add-vertex (sdl::point :x 170 :y 150))
	    (sdl::add-vertex (sdl::point :x 60 :y 150))))
	(sdl::with-color (a-col (sdl::color :r 255 :g 255 :b 255))
	  (sdl::with-shape (:points)
	    (sdl::add-vertex (sdl::point :x 60 :y 40))
	    (sdl::add-vertex (sdl::point :x 160 :y 10))
	    (sdl::add-vertex (sdl::point :x 170 :y 150))
	    (sdl::add-vertex (sdl::point :x 60 :y 150))))
	(sdl::with-color (a-col (sdl::color :r 126 :g 126 :b 126))
	  (sdl::with-bezier (:line-strip)
	    (sdl::add-vertex (sdl::point :x 60 :y 40))
	    (sdl::add-vertex (sdl::point :x 160 :y 10))
	    (sdl::add-vertex (sdl::point :x 170 :y 150))
	    (sdl::add-vertex (sdl::point :x 60 :y 150)))))
      (sdl::update-display)
      (sdl::with-events ()
	(:quit-event () t)
	(:video-expose-event () (sdl::update-display))))))
